language: php

sudo: false

php:
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: 7
        - php: hhvm

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pecl install crypto-0.1.1; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add ./tests/php.ini; fi;'
    - composer install --no-interaction
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/coveralls --no-interaction
