language: php

sudo: false

php:
    - 5.5.9
    - 5.6
    - 7
    - hhvm

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pecl install crypto-0.2.1; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension=crypto.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - composer install --no-interaction
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/coveralls --no-interaction
